### ISSUE TITLE
DockerHub build error: Argument list too long

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/PAVICS-e2e-workflow-tests#113]
Since December 19, 2022, DockerHub build has failing with the error below:

```
2023-01-17T06:39:15Z Building in Docker Cloud's infrastructure...
2023-01-17T06:39:15Z Cloning into '.'...
2023-01-17T06:39:16Z Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
2023-01-17T06:39:17Z Reset branch 'master'
2023-01-17T06:39:17Z Your branch is up to date with 'origin/master'.
2023-01-17T06:39:17Z KernelVersion: 5.4.0-1068-aws
2023-01-17T06:39:17Z Components: [{u'Version': u'20.10.15', u'Name': u'Engine', u'Details': {u'KernelVersion': u'5.4.0-1068-aws', u'Os': u'linux', u'BuildTime': u'2022-05-05T13:17:24.000000000+00:00', u'ApiVersion': u'1.41', u'MinAPIVersion': u'1.12', u'GitCommit': u'4433bf6', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.17.9'}}, {u'Version': u'1.6.9', u'Name': u'containerd', u'Details': {u'GitCommit': u'1c90a442489720eec95342e1789ee8a5e1b9536f'}}, {u'Version': u'1.1.4', u'Name': u'runc', u'Details': {u'GitCommit': u'v1.1.4-0-g5fd4c4d'}}, {u'Version': u'0.19.0', u'Name': u'docker-init', u'Details': {u'GitCommit': u'de40ad0'}}]
2023-01-17T06:39:17Z Arch: amd64
2023-01-17T06:39:17Z BuildTime: 2022-05-05T13:17:24.000000000+00:00
2023-01-17T06:39:17Z ApiVersion: 1.41
2023-01-17T06:39:17Z Platform: {u'Name': u'Docker Engine - Community'}
2023-01-17T06:39:17Z Version: 20.10.15
2023-01-17T06:39:17Z MinAPIVersion: 1.12
2023-01-17T06:39:17Z GitCommit: 4433bf6
2023-01-17T06:39:17Z Os: linux
2023-01-17T06:39:17Z GoVersion: go1.17.9
2023-01-17T06:39:17Z Buildkit: Starting build for index.docker.io/pavics/workflow-tests:latest...
2023-01-17T06:39:17Z Unexpected error
2023-01-17T06:39:17Z Encountered error: [Errno 7] Argument list too long
Traceback (most recent call last):
File "/stage/builder/runner.py", line 302, in _run
self.build()
File "/stage/builder/runner.py", line 226, in build
self._build()
File "/stage/builder/runner.py", line 210, in _build
cache_repo)
File "/stage/builder/buildkit.py", line 34, in build_image
decode=True, )
File "/stage/builder/buildkit.py", line 134, in _build_image
p = Popen(args_str, stdout=PIPE, stderr=STDOUT, shell=True)
File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
OSError: [Errno 7] Argument list too long
```
![Screenshot from 2023-01-17 01-47-10](https://user-images.githubusercontent.com/11966697/212828824-63426615-d860-49f3-ba32-a2db183a4750.png)

**Comment by tlvu** [comment]
Resolved since 2023-01-21
